stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cicd-test
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: RanJun
    notifier: c-sz4dg:n-zszc6
  condition:
  - Success
  - Changed
  - Failed
